#Requires -Version 7.0
<#
.SYNOPSIS
    Generates a report of mailbox-granting licenses by domain with automatic app registration
.DESCRIPTION
    Connects to Microsoft 365 tenants, auto-creates app registration if needed, and counts licenses that grant Exchange Online mailboxes
.PARAMETER TenantIDsPath
    Path to the Tenant IDs.xlsx file. Defaults to the standard location.
.PARAMETER OutputPath
    Path where the report will be saved
.PARAMETER AppName
    Name for the app registration (default: "VG-License-Reporter")
.PARAMETER CredentialStorePath
    Path to store app credentials (default: script directory)
#>
[CmdletBinding()]
param(
    [string]$TenantIDsPath = "C:\Users\Andy White\Volaris Group\GRP Data Security (Volaris Consolidated) - M365 Migrations\Tenant IDs.xlsx",
    [string]$OutputPath = "C:\Users\Andy White\Volaris Group\GRP Data Security (Volaris Consolidated) - M365 Migrations",
    [string]$AppName = "VG-License-Reporter",
    [string]$CredentialStorePath = $PSScriptRoot
)

$ErrorActionPreference = 'Stop'

# Load library
$libPath = Join-Path $PSScriptRoot 'lib.ps1'
if (Test-Path $libPath) {
    try { . $libPath }
    catch { Write-Warning "Failed to load lib.ps1: $_" }
}

function Write-Log {
    param([string]$Msg, [string]$Level = 'INFO')
    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss.fff'
    $line = "$timestamp  [$($Level.PadRight(5))]  $Msg"
    Write-Host $line
}

function Get-OrCreateAppRegistration {
    param(
        [string]$TenantId,
        [string]$TenantName,
        [string]$AppName
    )

    Write-Log "Checking for existing app registration in $TenantName..."

    try {
        # First, connect interactively to check/create the app
        Disconnect-MgGraph -ErrorAction SilentlyContinue | Out-Null
        Connect-MgGraph -TenantId $TenantId -Scopes "Application.ReadWrite.All", "Directory.Read.All" -NoWelcome

        # Check if app exists
        $existingApp = Get-MgApplication -Filter "displayName eq '$AppName'" -ErrorAction SilentlyContinue

        if ($existingApp) {
            Write-Log "App '$AppName' already exists (AppId: $($existingApp.AppId))"
            $appId = $existingApp.AppId
            $objectId = $existingApp.Id

            # Check if we have a stored secret for this tenant
            $credFile = Join-Path $CredentialStorePath "appcreds_$($TenantId).json"
            if (Test-Path $credFile) {
                Write-Log "Using existing credentials"
                $creds = Get-Content $credFile | ConvertFrom-Json
                return $creds
            } else {
                Write-Log "No stored credentials found, creating new secret..."
            }
        } else {
            Write-Log "Creating new app registration '$AppName'..."

            # Required resource access for Microsoft Graph
            $graphResourceId = "00000003-0000-0000-c000-000000000000" # Microsoft Graph

            # Application permissions we need
            $requiredPermissions = @(
                @{
                    Id = "7ab1d382-f21e-4acd-a863-ba3e13f7da61" # Directory.Read.All
                    Type = "Role"
                }
                @{
                    Id = "9a5d68dd-52b0-4cc2-bd40-abcf44ac3a30" # Application.Read.All
                    Type = "Role"
                }
                @{
                    Id = "b0afded3-3588-46d8-8b3d-9842eff778da" # Organization.Read.All
                    Type = "Role"
                }
            )

            # Build the required resource access object
            $resourceAccess = $requiredPermissions | ForEach-Object {
                @{
                    Id = $_.Id
                    Type = $_.Type
                }
            }

            $requiredResourceAccess = @(
                @{
                    ResourceAppId = $graphResourceId
                    ResourceAccess = $resourceAccess
                }
            )

            # Create the application
            $appParams = @{
                DisplayName = $AppName
                SignInAudience = "AzureADMyOrg"
                RequiredResourceAccess = $requiredResourceAccess
            }

            $newApp = New-MgApplication @appParams
            $appId = $newApp.AppId
            $objectId = $newApp.Id

            Write-Log "App created with AppId: $appId"

            # Wait a moment for app to propagate
            Start-Sleep -Seconds 3
        }

        # Create new client secret (valid for 2 years)
        Write-Log "Creating new client secret..."
        $secretName = "AutoGenerated-$(Get-Date -Format 'yyyyMMdd-HHmmss')"

        $passwordCred = @{
            DisplayName = $secretName
            EndDateTime = (Get-Date).AddYears(2)
        }

        $secret = Add-MgApplicationPassword -ApplicationId $objectId -PasswordCredential $passwordCred
        $clientSecret = $secret.SecretText

        Write-Log "Client secret created (expires: $($secret.EndDateTime))"

        # Check if service principal exists, create if not
        $sp = Get-MgServicePrincipal -Filter "appId eq '$appId'" -ErrorAction SilentlyContinue

        if (-not $sp) {
            Write-Log "Creating service principal..."
            $sp = New-MgServicePrincipal -AppId $appId
            Start-Sleep -Seconds 2
        }

        # Grant admin consent for the required permissions
        Write-Log "Granting admin consent for permissions..."

        # Get the Microsoft Graph service principal
        $graphSP = Get-MgServicePrincipal -Filter "appId eq '$graphResourceId'"

        foreach ($permission in $requiredPermissions) {
            try {
                $grant = @{
                    ClientId = $sp.Id
                    ConsentType = "AllPrincipals"
                    ResourceId = $graphSP.Id
                    Scope = $null
                    PrincipalId = $null
                }

                # For application permissions, we need to create app role assignments
                $appRoleAssignment = @{
                    PrincipalId = $sp.Id
                    ResourceId = $graphSP.Id
                    AppRoleId = $permission.Id
                }

                New-MgServicePrincipalAppRoleAssignment -ServicePrincipalId $sp.Id -BodyParameter $appRoleAssignment -ErrorAction SilentlyContinue | Out-Null
            } catch {
                # May already exist, that's okay
                Write-Log "Permission already granted or error: $($_.Exception.Message)" "WARN"
            }
        }

        Write-Log "Admin consent granted" "SUCCESS"

        # Store credentials securely
        $credFile = Join-Path $CredentialStorePath "appcreds_$($TenantId).json"
        $credObject = @{
            TenantId = $TenantId
            TenantName = $TenantName
            AppId = $appId
            ClientSecret = $clientSecret
            SecretExpires = $secret.EndDateTime
            CreatedDate = Get-Date
        }

        # Convert to JSON and save with restricted permissions
        $credObject | ConvertTo-Json | Out-File -FilePath $credFile -Encoding UTF8 -Force

        # Set file to read-only for current user
        $acl = Get-Acl $credFile
        $acl.SetAccessRuleProtection($true, $false)
        $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
            [System.Security.Principal.WindowsIdentity]::GetCurrent().Name,
            "Read",
            "Allow"
        )
        $acl.SetAccessRule($rule)
        Set-Acl $credFile $acl

        Write-Log "Credentials saved to: $credFile" "SUCCESS"

        return [PSCustomObject]$credObject

    } catch {
        Write-Log "ERROR: Failed to create/configure app registration: $_" "ERROR"
        throw
    } finally {
        Disconnect-MgGraph -ErrorAction SilentlyContinue | Out-Null
    }
}

function Connect-WithAppCredentials {
    param(
        [string]$TenantId,
        [string]$AppId,
        [string]$ClientSecret
    )

    try {
        Disconnect-MgGraph -ErrorAction SilentlyContinue | Out-Null

        # Create secure string for client secret
        $secureSecret = ConvertTo-SecureString $ClientSecret -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential($AppId, $secureSecret)

        # Connect using app credentials
        Connect-MgGraph -TenantId $TenantId -ClientSecretCredential $credential -NoWelcome

        return $true
    } catch {
        Write-Log "ERROR connecting with app credentials: $_" "ERROR"
        return $false
    }
}

# SKUs that grant Exchange Online mailboxes
$mailboxSKUs = @(
    'EXCHANGESTANDARD',
    'EXCHANGEENTERPRISE',
    'EXCHANGEARCHIVE_ADDON',
    'EXCHANGEDESKLESS',
    'EXCHANGETELCO',
    'OFFICESUBSCRIPTION',
    'O365_BUSINESS_ESSENTIALS',
    'O365_BUSINESS_PREMIUM',
    'SPB',
    'SPE_E3',
    'SPE_E5',
    'ENTERPRISEPACK',
    'ENTERPRISEPREMIUM',
    'DESKLESSPACK',
    'STANDARDPACK',
    'STANDARDWOFFPACK',
    'ENTERPRISEPACKLRG',
    'ENTERPRISEWITHSCAL',
    'SMB_BUSINESS',
    'SMB_BUSINESS_ESSENTIALS',
    'SMB_BUSINESS_PREMIUM',
    'MCOEV',
    'MCOMEETADV',
    'M365_F1',
    'M365_F3',
    'SPE_F1',
    'DEVELOPERPACK',
    'EXCHANGESTANDARD_STUDENT',
    'EXCHANGEENTERPRISE_FACULTY',
    'EXCHANGEENTERPRISE_STUDENT'
)

Write-Log "=== Mailbox License Report (Auto-App) Started ==="
Write-Log "Tenant IDs file: $TenantIDsPath"
Write-Log "App Name: $AppName"

# Check if file exists
if (-not (Test-Path $TenantIDsPath)) {
    Write-Log "ERROR: Tenant IDs file not found: $TenantIDsPath" "ERROR"
    exit 1
}

# Check if Microsoft Graph module is available
if (-not (Get-Module -ListAvailable -Name Microsoft.Graph.Authentication)) {
    Write-Log "ERROR: Microsoft.Graph module not installed. Install with: Install-Module Microsoft.Graph -Scope CurrentUser" "ERROR"
    exit 1
}

# Read Excel file using COM
Write-Log "Opening Excel file..."
$excel = $null
$workbook = $null
$tenants = [System.Collections.Generic.List[object]]::new()

try {
    $excel = New-Object -ComObject Excel.Application
    $excel.Visible = $false
    $excel.DisplayAlerts = $false

    $workbook = $excel.Workbooks.Open($TenantIDsPath)
    $worksheet = $workbook.Worksheets.Item(1)
    $usedRange = $worksheet.UsedRange

    $rowCount = $usedRange.Rows.Count
    $colCount = $usedRange.Columns.Count

    Write-Log "Found $rowCount rows and $colCount columns"

    # Process data rows (starting from row 2)
    for ($row = 2; $row -le $rowCount; $row++) {
        $tenantName = $usedRange.Cells.Item($row, 1).Text.Trim()

        # Skip empty rows
        if ([string]::IsNullOrWhiteSpace($tenantName)) {
            continue
        }

        # Check column J (column 10) and column N (column 14) for "Yes"
        $columnJValue = $usedRange.Cells.Item($row, 10).Text.Trim()
        $columnNValue = $usedRange.Cells.Item($row, 14).Text.Trim()

        # Skip if column J OR column N has "Yes" (case-insensitive)
        if ($columnJValue.ToLower() -eq "yes" -or $columnNValue.ToLower() -eq "yes") {
            $whichCol = if ($columnNValue.ToLower() -eq "yes") { "N" } elseif ($columnJValue.ToLower() -eq "yes") { "J" } else { "" }
            Write-Log "Row $row : [$tenantName] - Skipping (Column $whichCol = Yes)"
            continue
        }

        # Try to find domain/tenant ID in the row
        $tenantData = @{
            Name = $tenantName
            TenantId = $null
            Domain = $null
        }

        # Look for tenant ID or domain in various columns
        for ($col = 1; $col -le $colCount; $col++) {
            $cellValue = $usedRange.Cells.Item($row, $col).Text.Trim()

            # Check if it looks like a domain
            if ($cellValue -match '\.onmicrosoft\.com$' -or ($cellValue -match '\.\w{2,}$' -and $cellValue -match '@')) {
                $tenantData.Domain = $cellValue
            }

            # Check if it looks like a tenant GUID
            if ($cellValue -match '^[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}$') {
                $tenantData.TenantId = $cellValue
            }
        }

        if ($tenantData.Domain -or $tenantData.TenantId) {
            $tenants.Add([PSCustomObject]$tenantData)
            Write-Log "Found tenant: $tenantName (Domain: $($tenantData.Domain), TenantId: $($tenantData.TenantId))"
        } else {
            Write-Log "Skipping $tenantName - no domain or tenant ID found" "WARN"
        }
    }

} catch {
    Write-Log "ERROR reading Excel file: $_" "ERROR"
    throw
} finally {
    if ($workbook) {
        $workbook.Close($false)
        [System.Runtime.InteropServices.Marshal]::ReleaseComObject($workbook) | Out-Null
    }
    if ($excel) {
        $excel.Quit()
        [System.Runtime.InteropServices.Marshal]::ReleaseComObject($excel) | Out-Null
    }
    [GC]::Collect()
    [GC]::WaitForPendingFinalizers()
}

Write-Log "Found $($tenants.Count) tenants to process"

# Results collection
$results = [System.Collections.Generic.List[object]]::new()

foreach ($tenant in $tenants) {
    Write-Log ""
    Write-Log "=== Processing: $($tenant.Name) ===" "INFO"

    try {
        # Determine tenant ID to use
        $tenantIdToUse = if ($tenant.TenantId) { $tenant.TenantId } else { $tenant.Domain }

        if (-not $tenantIdToUse) {
            Write-Log "ERROR: No tenant ID or domain found" "ERROR"
            throw "No tenant ID or domain available"
        }

        # Check for existing credentials
        $credFile = Join-Path $CredentialStorePath "appcreds_$tenantIdToUse.json"

        if (Test-Path $credFile) {
            Write-Log "Loading existing app credentials..."
            $creds = Get-Content $credFile | ConvertFrom-Json

            # Check if secret is expired
            if ($creds.SecretExpires) {
                $expiryDate = [DateTime]$creds.SecretExpires
                if ($expiryDate -lt (Get-Date).AddDays(30)) {
                    Write-Log "Client secret expires soon ($expiryDate), will regenerate..." "WARN"
                    $creds = Get-OrCreateAppRegistration -TenantId $tenantIdToUse -TenantName $tenant.Name -AppName $AppName
                }
            }
        } else {
            Write-Log "No existing credentials found, setting up app registration..."
            $creds = Get-OrCreateAppRegistration -TenantId $tenantIdToUse -TenantName $tenant.Name -AppName $AppName
        }

        # Connect using app credentials
        Write-Log "Connecting to tenant with app credentials..."
        $connected = Connect-WithAppCredentials -TenantId $creds.TenantId -AppId $creds.AppId -ClientSecret $creds.ClientSecret

        if (-not $connected) {
            throw "Failed to connect with app credentials"
        }

        # Get organization details
        $org = Get-MgOrganization
        $primaryDomain = $org.VerifiedDomains | Where-Object { $_.IsDefault } | Select-Object -ExpandProperty Name

        Write-Log "Connected to: $primaryDomain"

        # Get all subscribed SKUs
        Write-Log "Querying licenses..."
        $skus = Get-MgSubscribedSku -All

        $mailboxLicenseCount = 0
        $mailboxSKUDetails = @()

        foreach ($sku in $skus) {
            $skuPartNumber = $sku.SkuPartNumber
            $grantsMailbox = $false

            # Check against known mailbox SKUs
            if ($mailboxSKUs -contains $skuPartNumber) {
                $grantsMailbox = $true
            }

            # Also check service plans for Exchange
            $exchangePlans = $sku.ServicePlans | Where-Object {
                $_.ServicePlanName -match 'EXCHANGE' -and
                $_.ProvisioningStatus -eq 'Success'
            }

            if ($exchangePlans) {
                $grantsMailbox = $true
            }

            if ($grantsMailbox) {
                $consumed = $sku.ConsumedUnits
                $mailboxLicenseCount += $consumed

                $mailboxSKUDetails += [PSCustomObject]@{
                    SKU = $skuPartNumber
                    Consumed = $consumed
                    Total = $sku.PrepaidUnits.Enabled
                }

                Write-Log "  $skuPartNumber : $consumed licenses consumed"
            }
        }

        # Add to results
        $results.Add([PSCustomObject]@{
            Domain = $primaryDomain
            TenantName = $tenant.Name
            TotalMailboxLicenses = $mailboxLicenseCount
            SKUDetails = ($mailboxSKUDetails | ForEach-Object { "$($_.SKU):$($_.Consumed)" }) -join '; '
            Status = 'Success'
        })

        Write-Log "Total mailbox licenses: $mailboxLicenseCount" "SUCCESS"

    } catch {
        Write-Log "ERROR processing tenant: $_" "ERROR"
        $results.Add([PSCustomObject]@{
            Domain = if ($tenant.Domain) { $tenant.Domain } else { "Unknown" }
            TenantName = $tenant.Name
            TotalMailboxLicenses = 0
            SKUDetails = "Error: $_"
            Status = 'Failed'
        })
    } finally {
        Disconnect-MgGraph -ErrorAction SilentlyContinue | Out-Null
    }
}

# Generate report
Write-Log ""
Write-Log "=== Generating Report ==="

$timestamp = Get-Date -Format 'yyyyMMdd_HHmmss'
$reportFile = Join-Path $OutputPath "MailboxLicenseReport_$timestamp.csv"
$summaryFile = Join-Path $OutputPath "MailboxLicenseSummary_$timestamp.txt"

# Export detailed CSV
$results | Export-Csv -Path $reportFile -NoTypeInformation -Encoding UTF8
Write-Log "Detailed report saved: $reportFile"

# Generate summary
$summary = @"
=== MAILBOX LICENSE REPORT SUMMARY ===
Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

TOTAL DOMAINS PROCESSED: $($results.Count)
SUCCESSFUL: $($results | Where-Object { $_.Status -eq 'Success' } | Measure-Object | Select-Object -ExpandProperty Count)
FAILED: $($results | Where-Object { $_.Status -eq 'Failed' } | Measure-Object | Select-Object -ExpandProperty Count)

=== MAILBOX LICENSE COUNT BY DOMAIN ===

"@

foreach ($result in $results | Sort-Object Domain) {
    $summary += "Domain: $($result.Domain)`n"
    $summary += "  Tenant Name: $($result.TenantName)`n"
    $summary += "  Mailbox Licenses: $($result.TotalMailboxLicenses)`n"
    $summary += "  Status: $($result.Status)`n"
    if ($result.SKUDetails -and $result.Status -eq 'Success') {
        $summary += "  SKU Breakdown: $($result.SKUDetails)`n"
    }
    $summary += "`n"
}

$totalLicenses = ($results | Where-Object { $_.Status -eq 'Success' } | Measure-Object -Property TotalMailboxLicenses -Sum).Sum
$summary += "=== GRAND TOTAL: $totalLicenses MAILBOX LICENSES ===`n"

# Save summary
$summary | Out-File -FilePath $summaryFile -Encoding UTF8
Write-Log "Summary saved: $summaryFile"

# Display summary to console
Write-Log ""
Write-Host $summary

Write-Log ""
Write-Log "=== Mailbox License Report Complete ===" "SUCCESS"
Write-Log "Detailed CSV: $reportFile"
Write-Log "Summary TXT: $summaryFile"
Write-Log ""
Write-Log "App credentials stored in: $CredentialStorePath\appcreds_*.json"
Write-Log "These will be reused on subsequent runs for automatic authentication."
