#Requires -Version 7.0
<#
.SYNOPSIS
    One-time setup: Creates app registration for license reporting
.DESCRIPTION
    Run this script ONCE per tenant to create the app registration.
    After setup completes, Check-TenantLicenses.ps1 will use the
    stored credentials automatically.
.PARAMETER TenantId
    The tenant ID or domain (e.g., "aioneducation.onmicrosoft.com")
.PARAMETER TenantName
    Friendly name for this tenant (e.g., "Celcat")
.EXAMPLE
    .\Setup-LicenseReportApp.ps1 -TenantId "aioneducation.onmicrosoft.com" -TenantName "Celcat"
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$TenantId,

    [Parameter(Mandatory)]
    [string]$TenantName,

    [string]$AppName = "VG-License-Reporter",

    [string]$CredentialStorePath = $PSScriptRoot
)

$ErrorActionPreference = 'Stop'

function Write-Log {
    param([string]$Msg, [string]$Level = 'INFO')
    $colors = @{
        'INFO' = 'Cyan'
        'SUCCESS' = 'Green'
        'WARN' = 'Yellow'
        'ERROR' = 'Red'
    }
    Write-Host "[$Level] $Msg" -ForegroundColor $colors[$Level]
}

Write-Host ""
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "  License Report App Setup" -ForegroundColor Cyan
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host ""
Write-Log "Tenant: $TenantName ($TenantId)"
Write-Log "App Name: $AppName"
Write-Host ""

# Check if already set up
$credFile = Join-Path $CredentialStorePath "appcreds_$($TenantId).json"
if (Test-Path $credFile) {
    $existing = Get-Content $credFile | ConvertFrom-Json
    Write-Log "App registration already exists!" "WARN"
    Write-Log "  App ID: $($existing.AppId)" "WARN"
    Write-Log "  Created: $($existing.CreatedDate)" "WARN"
    Write-Host ""
    $continue = Read-Host "Create new credentials anyway? (y/N)"
    if ($continue -ne 'y') {
        Write-Log "Setup cancelled" "WARN"
        exit 0
    }
}

# Check Microsoft.Graph module
Write-Log "Checking Microsoft.Graph module..."
if (-not (Get-Module -ListAvailable -Name Microsoft.Graph.Applications)) {
    Write-Log "Installing Microsoft.Graph.Applications..." "WARN"
    Install-Module -Name Microsoft.Graph.Applications -Scope CurrentUser -Force -AllowClobber
}

try {
    # Connect with interactive browser auth
    Write-Log "Opening browser for authentication..."
    Write-Log "Sign in as a Global Administrator or Application Administrator" "WARN"
    Write-Host ""

    Import-Module Microsoft.Graph.Authentication
    Disconnect-MgGraph -ErrorAction SilentlyContinue | Out-Null
    Connect-MgGraph -TenantId $TenantId -Scopes "Application.ReadWrite.All" -NoWelcome

    Write-Log "Connected successfully!" "SUCCESS"
    Write-Host ""

    # Check if app exists
    Write-Log "Checking for existing app registration..."
    $existingApp = Get-MgApplication -Filter "displayName eq '$AppName'" -ErrorAction SilentlyContinue

    if ($existingApp) {
        Write-Log "App exists: $($existingApp.AppId)" "SUCCESS"
        $appId = $existingApp.AppId
        $objectId = $existingApp.Id
    } else {
        Write-Log "Creating new app registration..." "WARN"

        # Microsoft Graph resource ID
        $graphResourceId = "00000003-0000-0000-c000-000000000000"

        # Required permissions for license reporting
        $requiredPermissions = @(
            @{
                Id = "7ab1d382-f21e-4acd-a863-ba3e13f7da61" # Directory.Read.All
                Type = "Role"
            }
            @{
                Id = "9a5d68dd-52b0-4cc2-bd40-abcf44ac3a30" # Application.Read.All
                Type = "Role"
            }
            @{
                Id = "b0afded3-3588-46d8-8b3d-9842eff778da" # Organization.Read.All
                Type = "Role"
            }
        )

        # Build required resource access
        $resourceAccess = $requiredPermissions | ForEach-Object {
            @{
                Id = $_.Id
                Type = $_.Type
            }
        }

        $requiredResourceAccess = @(
            @{
                ResourceAppId = $graphResourceId
                ResourceAccess = $resourceAccess
            }
        )

        # Create the application
        $appParams = @{
            DisplayName = $AppName
            SignInAudience = "AzureADMyOrg"
            RequiredResourceAccess = $requiredResourceAccess
        }

        $newApp = New-MgApplication @appParams
        $appId = $newApp.AppId
        $objectId = $newApp.Id

        Write-Log "App created: $appId" "SUCCESS"
        Start-Sleep -Seconds 3
    }

    # Create new client secret (valid for 2 years)
    Write-Log "Creating new client secret..."
    $secretName = "AutoGenerated-$(Get-Date -Format 'yyyyMMdd-HHmmss')"

    $passwordCred = @{
        DisplayName = $secretName
        EndDateTime = (Get-Date).AddYears(2)
    }

    $secret = Add-MgApplicationPassword -ApplicationId $objectId -PasswordCredential $passwordCred
    $clientSecret = $secret.SecretText

    Write-Log "Client secret created (expires: $($secret.EndDateTime.ToString('yyyy-MM-dd')))" "SUCCESS"

    # Check if service principal exists, create if not
    $sp = Get-MgServicePrincipal -Filter "appId eq '$appId'" -ErrorAction SilentlyContinue

    if (-not $sp) {
        Write-Log "Creating service principal..."
        $sp = New-MgServicePrincipal -AppId $appId
        Start-Sleep -Seconds 2
        Write-Log "Service principal created" "SUCCESS"
    } else {
        Write-Log "Service principal exists" "SUCCESS"
    }

    # Grant admin consent for the required permissions
    Write-Log "Granting admin consent for permissions..."

    # Get the Microsoft Graph service principal (use single quotes in filter)
    $graphSP = Get-MgServicePrincipal -Filter "appId eq '00000003-0000-0000-c000-000000000000'"

    $permissionNames = @{
        "7ab1d382-f21e-4acd-a863-ba3e13f7da61" = "Directory.Read.All"
        "9a5d68dd-52b0-4cc2-bd40-abcf44ac3a30" = "Application.Read.All"
        "b0afded3-3588-46d8-8b3d-9842eff778da" = "Organization.Read.All"
    }

    foreach ($permission in $requiredPermissions) {
        # Check if permission already exists
        $existingAssignment = Get-MgServicePrincipalAppRoleAssignment -ServicePrincipalId $sp.Id -ErrorAction SilentlyContinue |
            Where-Object { $_.AppRoleId -eq $permission.Id -and $_.ResourceId -eq $graphSP.Id }

        if ($existingAssignment) {
            Write-Log "  Already granted: $($permissionNames[$permission.Id])" "SUCCESS"
        } else {
            try {
                $appRoleAssignment = @{
                    PrincipalId = $sp.Id
                    ResourceId = $graphSP.Id
                    AppRoleId = $permission.Id
                }

                New-MgServicePrincipalAppRoleAssignment -ServicePrincipalId $sp.Id -BodyParameter $appRoleAssignment | Out-Null
                Write-Log "  Granted: $($permissionNames[$permission.Id])" "SUCCESS"
            } catch {
                Write-Log "  Warning on $($permissionNames[$permission.Id]): $($_.Exception.Message)" "WARN"
            }
        }
    }

    # Verify permissions were granted
    Start-Sleep -Seconds 2
    $verifiedCount = 0
    foreach ($permission in $requiredPermissions) {
        $verifyAssignment = Get-MgServicePrincipalAppRoleAssignment -ServicePrincipalId $sp.Id -ErrorAction SilentlyContinue |
            Where-Object { $_.AppRoleId -eq $permission.Id -and $_.ResourceId -eq $graphSP.Id }

        if ($verifyAssignment) {
            $verifiedCount++
        }
    }

    if ($verifiedCount -eq $requiredPermissions.Count) {
        Write-Log "All permissions verified successfully" "SUCCESS"
    } else {
        Write-Log "WARNING: Only $verifiedCount of $($requiredPermissions.Count) permissions verified" "WARN"
        Write-Log "You may need to manually grant admin consent in the Azure Portal" "WARN"
    }

    Write-Log "Admin consent completed" "SUCCESS"

    # Store credentials securely
    $credObject = @{
        TenantId = $TenantId
        TenantName = $TenantName
        AppId = $appId
        ClientSecret = $clientSecret
        SecretExpires = $secret.EndDateTime
        CreatedDate = Get-Date
    }

    $credObject | ConvertTo-Json | Out-File -FilePath $credFile -Encoding UTF8 -Force
    Write-Log "Credentials saved to: $credFile" "SUCCESS"

    Disconnect-MgGraph -ErrorAction SilentlyContinue | Out-Null

    Write-Host ""
    Write-Host "=========================================" -ForegroundColor Green
    Write-Host "  Setup Complete!" -ForegroundColor Green
    Write-Host "=========================================" -ForegroundColor Green
    Write-Host ""
    Write-Log "App ID: $appId" "SUCCESS"
    Write-Log "Secret expires: $($secret.EndDateTime.ToString('yyyy-MM-dd'))" "SUCCESS"
    Write-Host ""
    Write-Log "Check-TenantLicenses.ps1 will now use these credentials automatically" "SUCCESS"
    Write-Host ""

} catch {
    Write-Log "Setup failed: $_" "ERROR"
    Write-Log $_.ScriptStackTrace "ERROR"
    exit 1
}
